services:
  backend_1:
    build:
      target: dev
    ports:
      - 4001:3000
    volumes:
      - ./app/backend/:/app/backend/

  backend_2:
    build:
      target: dev
    ports:
      - 4000:3000
    volumes:
      - ./app/backend/:/app/backend/

  frontend_1:
    build:
      target: dev
    ports:
      - 6002:5000
    volumes:
      - ./app/frontend/:/app/frontend/

  frontend_2:
    build:
      target: dev
    ports:
      - 6001:5000
    volumes:
      - ./app/frontend/:/app/frontend/
