services:
  backend:
    build:
      target: start
    ports:
      - 3001:3001
    volumes:
      - ./app/backend/:/app/backend/

  frontend:
    build:
      target: start
    ports:
      - 5001:5001
    volumes:
      - ./app/frontend/:/app/frontend/
